# Generated by Django 5.2.4 on 2025-07-11 08:13

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("support", "Support"),
                    ("driver", "Driver"),
                    ("customer", "Customer"),
                ],
                default=users.models.Role["CUSTOMER"],
                max_length=50,
            ),
        ),
    ]
