GET http://localhost:8002/healthcheck HTTP/1.1
content-type: application/json


### Make Order
POST http://localhost:8002/api/orders HTTP/1.1
content-type: application/json

{
    "order": [
        {
            "dish": "Salad",
            "quantity": 3
        },
        {
            "dish": "Water",
            "quantity": 2
        }
    ]
}