# Generated by Django 5.2.4 on 2025-07-11 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_order_total_alter_dish_restaurant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="food.order",
            ),
        ),
    ]
