# Generated by Django 5.2.4 on 2025-07-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
