# Generated by Django 5.2.4 on 2025-07-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_alter_order_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="adress",
            new_name="address",
        ),
    ]
