name: Code quality check

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  - push
    - branches:
      -main

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install dependencies
        run: pip install pipenv && pipenv sync --dev --system
      - name: code quality check
        run: flake8 .
